version: '3.4'

services:
  ecommerce.api:
    image: ${DOCKER_REGISTRY-}ecommerceapi
    container_name: ecommerce.api
    build:
      context: .
      dockerfile: Api/ECommerce.Api/Dockerfile
    ports:
     - "5000:5000"
     - "5001:5001"

  ecommerce.database:
    image: postgres:latest 
    container_name: ecommerce.database
    environment: 
     - POSTGRES_DB=ecommercedb
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=postgres
    volumes:
     - ./.containers/ecommers-db:/var/lib/postgresql/data 
    ports:
     - 5432:5432